### ISSUE TITLE
Mapper not generating rules for value_as_number in the observation domain

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#711] opened 2024-05-14 08:42 UTC
**Issue**
value_as_number is the field that records numeric value(s) of the source field or source field value(s) mapped to a concept_id in Measurement and Observation Domain. This is working perfectly fine for Measurement but not Observation. I believe this was not always the case, however, I have just noticed it

**To reproduce**
Go to scan report # 623
check mapping against concept 35815526 - Age at event

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by AndyRae** [comment] 2024-05-14 19:11
Thanks Erum - we will investigate.

**Comment by AndyRae** [comment] 2024-05-14 19:17
Relevant: https://github.com/Health-Informatics-UoN/CaRROT-Mapper/blob/7032dff83bfbb5d896ca2e3845ad82c5e76efd92/app/shared/shared/services/rules.py#L371

Given there is direct code for the `measurement` domain, and nothing for the `observation` domain, my initial thinking is that this is not a regression. But will take a further look.

**Comment by AndyRae** [comment] 2024-08-09 07:43
Just closing this as a duplicate of #647

**Closed by AndyRae** 2024-08-09 07:43 UTC
Labels: duplicate, feature request, omop
